### ISSUE TITLE
cannot serialize std::bitset on OSX with clang

### ISSUE THREAD

**Issue by imichaelmiers** [USCiLab/cereal#145]
The minimal code to serialize a bitset fails to compile on OSX 10.9 using clang  against both v1.0.0, master (7121e91e6ab8c3e6a6516d9d9c3e6804e6f65245), and what brew has installed.

$ uname -a 
Darwin [REDACTED] 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64

$  g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

Code : 

```
#include <string>
#include <cereal/archives/binary.hpp>
#include <cereal/types/common.hpp>
#include <cereal/types/bitset.hpp>
#include <bitset>
int main(){
        std::stringstream ss;
        std::bitset<256> a;
        {
            cereal::BinaryOutputArchive oarchive(ss);
            oarchive(a);
        }
        {
            cereal::BinaryInputArchive iarchive(ss); 
            iarchive(a);
        }
}
```

$ g++ -std=c++11 mwx.cpp 
In file included from mwx.cpp:2:
In file included from /usr/local/include/cereal/archives/binary.hpp:32:
/usr/local/include/cereal/cereal.hpp:444:9: error: static_assert failed "Trying to serialize an
      unserializable type with an output archive. \n\n Types must either have a serialize function, load/save
      pair, or load_minimal/save_minimal pair (you may not mix these). \n Use specialization (see access.hpp)
      if you need to disambiguate between serialize vs load/save functions. \n In addition, you may not mix
      versioned with non-versioned serialization functions. \n Serialize functions generally have the
      following signature: \n\n template<class Archive> \n void serialize(Archive & ar) \n { \n ar( member1,
      member2, member3 ); \n } \n\n "
        static_assert(traits::is_output_serializable<T, ArchiveType>::value, "Trying to serialize an ...
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/cereal/cereal.hpp:325:15: note: in instantiation of function template specialization
      'cereal::OutputArchive<cereal::BinaryOutputArchive, 1>::processImplstd::__1::basic_string<char >'
      requested here
        self->processImpl( head );
              ^
/usr/local/include/cereal/cereal.hpp:241:15: note: in instantiation of function template specialization
      'cereal::OutputArchive<cereal::BinaryOutputArchive, 1>::processstd::__1::basic_string<char >'
      requested here
        self->process( std::forward<Types>( args )... );
              ^
/usr/local/include/cereal/types/bitset.hpp:71:9: note: in instantiation of function template specialization
      'cereal::OutputArchive<cereal::BinaryOutputArchive, 1>::operator()std::__1::basic_string<char >'
      requested here
        ar( _CEREAL_NVP("data", bits.to_string()) );
        ^
/usr/local/include/cereal/cereal.hpp:400:9: note: in instantiation of function template specialization
      'cereal::save<cereal::BinaryOutputArchive, 256>' requested here
        save(_self, t);
        ^
/usr/local/include/cereal/cereal.hpp:325:15: note: in instantiation of function template specialization
      'cereal::OutputArchive<cereal::BinaryOutputArchive, 1>::processImplstd::__1::bitset<256 >' requested
      here
        self->processImpl( head );
              ^
/usr/local/include/cereal/cereal.hpp:241:15: note: in instantiation of function template specialization
      'cereal::OutputArchive<cereal::BinaryOutputArchive, 1>::processstd::__1::bitset<256 &>' requested
      here
        self->process( std::forward<Types>( args )... );
              ^
mwx.cpp:13:13: note: in instantiation of function template specialization
      'cereal::OutputArchive<cereal::BinaryOutputArchive, 1>::operator()std::__1::bitset<256 &>' requested
      here
                                oarchive(a);
                                        ^
In file included from mwx.cpp:2:
In file included from /usr/local/include/cereal/archives/binary.hpp:32:
/usr/local/include/cereal/cereal.hpp:827:9: error: static_assert failed "Trying to serialize an
      unserializable type with an output archive. \n\n Types must either have a serialize function, load/save
      pair, or load_minimal/save_minimal pair (you may not mix these). \n Use specialization (see access.hpp)
      if you need to disambiguate between serialize vs load/save functions. \n In addition, you may not mix
      versioned with non-versioned serialization functions. \n Serialize functions generally have the
      following signature: \n\n template<class Archive> \n void serialize(Archive & ar) \n { \n ar( member1,
      member2, member3 ); \n } \n\n "
        static_assert(traits::is_output_serializable<T, ArchiveType>::value, "Trying to serialize an ...
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/cereal/cereal.hpp:705:15: note: in instantiation of function template specialization
      'cereal::InputArchive<cereal::BinaryInputArchive, 1>::processImplstd::__1::basic_string<char >'
      requested here
        self->processImpl( head );
              ^
/usr/local/include/cereal/cereal.hpp:608:9: note: in instantiation of function template specialization
      'cereal::InputArchive<cereal::BinaryInputArchive, 1>::processstd::__1::basic_string<char &>'
      requested here
        process( std::forward<Types>( args )... );
        ^
/usr/local/include/cereal/types/bitset.hpp:102:9: note: in instantiation of function template specialization
      'cereal::InputArchive<cereal::BinaryInputArchive, 1>::operator()std::__1::basic_string<char &>'
      requested here
        ar( _CEREAL_NVP("data", b) );
        ^
/usr/local/include/cereal/cereal.hpp:780:9: note: in instantiation of function template specialization
      'cereal::load<cereal::BinaryInputArchive, 256>' requested here
        load(_self, t);
        ^
/usr/local/include/cereal/cereal.hpp:705:15: note: in instantiation of function template specialization
      'cereal::InputArchive<cereal::BinaryInputArchive, 1>::processImplstd::__1::bitset<256 >' requested
      here
        self->processImpl( head );
              ^
/usr/local/include/cereal/cereal.hpp:608:9: note: in instantiation of function template specialization
      'cereal::InputArchive<cereal::BinaryInputArchive, 1>::processstd::__1::bitset<256 &>' requested here
        process( std::forward<Types>( args )... );
        ^
mwx.cpp:17:17: note: in instantiation of function template specialization
      'cereal::InputArchive<cereal::BinaryInputArchive, 1>::operator()std::__1::bitset<256 &>' requested
      here
                        iarchive(a);
                                ^
2 errors generated.
