### ISSUE TITLE
'cereal/cereal.hpp' file not found

### ISSUE THREAD

**Issue by hudspero** [USCiLab/cereal#212]
Using Xcode 6.4, compiling with GCC 4.2.1. Include folder is dropped into main project area and directory chain is not broken. I've included "./include/cereal/archives/json.hpp", but adding "./include/cereal/cereal.hpp" did not resolve the issue. Is it because my compiler is outdated?

**Comment by AzothAmmo** [comment]
I'm not very familiar with using Xcode but GCC 4.2.1 is not supported by cereal.  The earliest GCC we work with is 4.7.  Your error is probably due to a configuration problem though, but you'd eventually run into compilation errors because of the older C++ version.

**Comment by hudspero** [comment]
If it is a configuration problem, can you see where I've improperly set up the folder structure?
![can t_find_cereal](https://cloud.githubusercontent.com/assets/12946207/8857223/1ffcc392-3125-11e5-8dcd-49a54d559ca0.png)

**Comment by AzothAmmo** [comment]
Your questions about set-up are better suited for somewhere like Stack Overflow or perhaps some XCode-centric place, but take a look at [this post](http://stackoverflow.com/questions/12654013/how-to-make-g-search-for-header-files-in-a-specific-directory).  You need to learn about the `-I` parameter.

**Comment by hudspero** [comment]
Thank you very much. I will take these into consideration.

**Comment by JosephLaurino** [comment]
I added an xcode folder under my fork of cereal [xcode](https://github.com/JosephLaurino/cereal/tree/master/xcode) 

it has some notes on how to get cereal up and running in xcode
