### ISSUE TITLE
Getting compilation error in Xcode 5.1 (Clang based on LLVM 3.4)

### ISSUE THREAD

**Issue by valleyman86** [USCiLab/cereal#104]
I am getting the following error during compilation after upgrading to 1.0.0 from 0.9.1 Cereal. I can't seem to figure out the cause but it feels like it may be associated with C++ 11. This same code worked before and all i did was update the library. I tried running the basic sample from the readme and that failed to load the cereal header as well. Any ideas?

AnimationSerializer/cereal/details/traits.hpp:1176:21: Expected member name or ';' after declaration specifiers

AnimationSerializer/AnimationSerializer/RTSAnimationSpriteData.mm:9:9: In file included from AnimationSerializer/AnimationSerializer/RTSAnimationSpriteData.mm:9:

AnimationSerializer/AnimationSerializer/RTSAnimationSpriteData.h:12:10: In file included from AnimationSerializer/AnimationSerializer/RTSAnimationSpriteData.h:12:

AnimationSerializer/AnimationSerializer/RTS/RTSAnimationSpriteData.h:13:10: In file included from AnimationSerializer/AnimationSerializer/RTS/RTSAnimationSpriteData.h:13:

AnimationSerializer/cereal/types/string.hpp:33:10: In file included from AnimationSerializer/cereal/types/string.hpp:33:

AnimationSerializer/cereal/cereal.hpp:42:10: In file included from AnimationSerializer/cereal/cereal.hpp:42:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/AssertMacros.h:1291:28: Expanded from macro 'check'

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/AssertMacros.h:280:5: Expanded from macro '__Check'

**Comment by pmoulon** [comment]
@AzothAmmo Any news about clang compatibility (since #75)?

**Comment by AzothAmmo** [comment]
We don't have any compatibility issues that I am aware of other that the issue here which is fixed using the macro mentioned. #75 only refers to our automated build system, which we haven't taken the time to configure for clang.

**Comment by winduptoy** [comment]
What's the current status of this?

I can't compile with Xcode/Clang either. I've done nothing besides importing cereal.

**Comment by winduptoy** [comment]
Sorry about that. I was able to resolve this by switching Clang to C++11 mode (Apple LLVM 7.0 - Language - C++ :arrow_forward: C++ Language Dialect :arrow_forward: C++11 [-std=c++11])

It's 2015, I would have thought C++11 would have been default by now...

**Comment by AzothAmmo** [comment]
This is a pretty obscure problem that we don't really have a good place for in the documentation - closing for now. Anyone who runs into this should be able to find this issue easily by searching for a few of the error messages and adding in the word "cereal."
